apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - name: pos
        image: cruzazul-pos:v1
        ports:
        - containerPort: 8000