services:
  frontend:
    build: ./frontend
    container_name: cruzazul_frontend
    ports:
      - "80:3000" 
    networks:
      - azul-net
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./database
    container_name: cruzazul_db
    environment:
      POSTGRES_DB: cruzazul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - azul-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  azul-net:
    driver: bridge